### ISSUE TITLE
Use common listener for device type

### ISSUE THREAD

**Issue by christopherlim98** [opengovsg/askgovsg#1045]
Currently there are 3 listeners to detect device type across Header, SearchResults and HomePage components. 

Would be good to explore a way to unify these 3 listeners by creating a shared context for device type.

**Comment by nigel0511** [comment]
Hi! I am interested in this issue, refactoring/extracting the detect device across Header, SearchResults and HomPage components using customise hook and make it reusable to other components. can I be assigned?

**Comment by christopherlim98** [comment]
It's yours! @siuting0511
