### ISSUE TITLE
Setup storybook for local development

### ISSUE THREAD

**Issue by christopherlim98** [opengovsg/askgovsg#1047]
**Is your feature request related to a problem? Please describe.**
As part of plans to integrate chromatic for UI regression testing, we need to first setup [storybook](https://storybook.js.org/).

Some benefits of Storybook:

- Documentation: Components will be captured as stories, which are isolated views that can serve as UI documentation. 
- Spot tests: Components can be viewed in isolation for manual spot testing. 
- Snapshot tests: Setup baselines for rendered markup to identify and review changes

More details on [design doc (WIP)](https://docs.google.com/document/d/1VWrvp-23UnfBi9AP-UELiwuN2zWyyhM_X9udybx_THw/edit)

**Comment by LoneRifle** [comment]
Fixed by #1054
