### ISSUE TITLE
When user types in >150 character in question input, show a clearer error message

### ISSUE THREAD

**Issue by khaleedah** [opengovsg/askgovsg#1053]
**Describe the bug**
As most agency users are copy pasting FAQ from their mastersheet, the character count doesn't count down but instead just shows zero

**To Reproduce**
1. Login
2. Click on 'Post Question'
3. Paste into the question box 

![image](https://user-images.githubusercontent.com/87360573/147729227-b37cdc4d-1b36-4642-ac11-c52e27eb2b2e.png)

**Expected behavior**
Suggestion: Provide clearer error messages

If user is over character limit, in real time, show `X characters over`
(see on right)
![image](https://user-images.githubusercontent.com/87360573/147729799-70bf20bc-b53a-4460-a4da-236894cff979.png)

**Comment by nigel0511** [comment]
Hi! I am interested in working on this, however I am not authorised to log in. Please let me know which component is responsible.
