### ISSUE TITLE
Use full names of agencies on home page

### ISSUE THREAD

**Issue by LoneRifle** [opengovsg/askgovsg#1405]
The AskGov homepage currently uses acronyms which may not be immediately recognisable by members of the public:
![image](https://user-images.githubusercontent.com/10572368/158091567-1e74f259-8e78-4eb5-9844-cc9a4adcac1e.png)

Expanding the acronyms would not only help users identify the agency which may have desired answers, but will also be consistent with agency-specific pages, which use full phrases for topic names:
![image](https://user-images.githubusercontent.com/10572368/158091654-f156806c-03a9-4721-b4de-b3896fec6443.png)

**Comment by nigel0511** [comment]
Hi! I would like to contribute to this, can I be assigned?

**Comment by LoneRifle** [comment]
@siuting0511 Sure! Thanks for looking into this.

**Comment by nigel0511** [comment]
Hi! I am looking into the code and as far as I am concern there are two ways to implement the change:

1. There's no query to request list of agencies data from server, the existing queries is to get all short name, get single agency by id and get single agency by shortname. To show all the agencies long name,  a new query will be needed to request all agencies data/long name, that will need to be implemented both frontend and backend.

2. To hard code all the agencies name and fetch by shortname, of cause this is undesirable and make code hard to expand later on.

Please comments and suggest alternative if appropriate @LoneRifle . Thank you.

**Comment by LoneRifle** [comment]
@siuting0511 - let's go with 1. You can repurpose the following block so that it lists all the agencies rather than just query for a single agency:
https://github.com/opengovsg/askgovsg/blob/f953209f9204cc8016044a514db08f515ea05dc2/server/src/modules/agency/agency.routes.ts#L23-L27
