### ISSUE TITLE
Replace "Help Center (alpha)" with AskGov logo

### ISSUE THREAD

**Issue by LoneRifle** [opengovsg/askgovsg#16]
Doesn't have to be the actual logo yet, can just be in text form just like "Help Center" now. Continue to include the "alpha".

**Comment by khaleedah** [comment]
![AskGov Logo White](https://user-images.githubusercontent.com/87360573/131619423-03c69d4b-6c4d-4a74-a9c6-687487a39210.png)


@nauynix here you go, it's exported from the [Figma file.](https://www.figma.com/file/yATTXTZ5Goy9XDy5qooSO3/AskGov-Design-System?node-id=2153%3A1459) ping if you need it in another size
