### ISSUE TITLE
text overflow when inserting image

### ISSUE THREAD

**Issue by chongzixin** [opengovsg/askgovsg#172]
![image](https://user-images.githubusercontent.com/3539074/131431220-5378264d-9989-43b4-9a42-71d1ce0690fe.png)

**Comment by nauynix** [comment]
Browser specific
## Firefox
<img width="346" alt="image" src="https://user-images.githubusercontent.com/20250559/132283838-799e1922-cd60-45c8-849d-d6bca71495c9.png">

## Chrome and safari
<img width="466" alt="image" src="https://user-images.githubusercontent.com/20250559/132283919-8deeb144-f33d-4edf-80ac-94a587fbc2b0.png">
