### ISSUE TITLE
Submit an Enquiry modal form is not optimised for mobile

### ISSUE THREAD

**Issue by khaleedah** [opengovsg/askgovsg#179]
**Describe the bug**
Submit an Enquiry modal form is not optimised for mobile [doesn't work for either android / iOS]

**To Reproduce**
1. On mobile, go to 'https://ask.gov.sg/agency/parkingsg'
2. Click on 'Submit an Enquiry'
3. See error

**Expected behavior**
Modal should be within phone screen

**Screenshots**

https://user-images.githubusercontent.com/87360573/131465573-a43a3146-2d90-4b89-9e1e-4213ccacf195.mov

**Comment by LoneRifle** [comment]
Fixed in #176
