### ISSUE TITLE
on mobile view, selecting a question at the bottom of the home page brings the user to the bottom of the `/questions` page too

### ISSUE THREAD

**Issue by chongzixin** [opengovsg/askgovsg#186]
**Steps to reproduce:**
1. Go to https://ask.gov.sg/agency/parkingsg on mobile
2. Scroll to the bottom of the page, click on the last question
3. `/questions` is loaded, but scrolled to the bottom of the page

**Ideal behaviour:**
Load `/questions` at the top of the page.

**Screenshots:**
Click on `my car has multiple drivers....`
![image](https://user-images.githubusercontent.com/3539074/131473525-c285ac8a-38d8-4265-9a92-87483eaaedf9.png)

Loads the below, user needs to scroll up.
![image](https://user-images.githubusercontent.com/3539074/131473639-c356f9dd-2487-4635-8100-dc900c744bdb.png)

**Comment by nauynix** [comment]
Scroll to top was added to legalese pages, but not the other pages. Modifying it to scroll on all pages
