### ISSUE TITLE
npm run server requires docker 

### ISSUE THREAD

**Issue by nauynix** [opengovsg/askgovsg#220]
**Describe the bug**
`npm run server` no longer works because it depends on docker, specifically the `db`. So to develop the backend, `npm run dev` is still needed. This makes the `readme` misleading as new users will think `npm run server` is all they need to work on the backend.

**Comment by LoneRifle** [comment]
This has always been the case - `npm run server` would always fail on a dev machine without an active database server. The difference is that previously you had MySQL running in the background on your dev machine, whereas now, the dependency is made more explicit via docker.

The readme should hence explicitly state this dependency.
