### ISSUE TITLE
HTTP status code should be 404 for non-existent paths

### ISSUE THREAD

**Issue by LoneRifle** [opengovsg/askgovsg#256]
**Describe the bug**
If a non-existent page is visited, the service returns 200 OK rather than 404, even though the page does not actually exist.

**To Reproduce**
Visit ask.gov.sg/does-not-exist - observe that the service returns 200 OK even though the page indicates Not Found

**Expected behavior**
HTTP status should be 404

**Comment by LinHuiqing** [comment]
Fixed by PR https://github.com/opengovsg/askgovsg/pull/494.
