### ISSUE TITLE
Create email address: `admin@ask.gov.sg` and `enquiries@ask.gov.sg`

### ISSUE THREAD

**Issue by chongzixin** [opengovsg/askgovsg#27]
Feedback from IPOS.

Email group should consist of users currently in `askgov@open.gov.sg`.

> Email correspondence – one of our colleagues mentioned that the “@open.gov.sg” may create a wrong impression that their email is “open”. Understand that it’s part of the Open Gov products from GovTech. For your consideration.

**Comment by nauynix** [comment]
Also create `feedback@ask.gov.sg` for the enquiry email

**Comment by LoneRifle** [comment]
Maybe enquiries might be a better mail
