### ISSUE TITLE
Migrate Spinner to Chakra + TypeScript

### ISSUE THREAD

**Issue by LoneRifle** [opengovsg/askgovsg#273]
As a gentle introduction to the frontend part of the codebase,
migrate the Spinner to use Chakra components and TypeScript

**Comment by LinHuiqing** [comment]
Not sure if this is a dumb question, but is there a need for a custom component file for the spinner? Would it make sense for us to use the Spinner component from Chakra directly? The one implemented in https://github.com/opengovsg/askgovsg/pull/311 looks very similar based on the Chakra docs: https://chakra-ui.com/docs/feedback/spinner

If we want customisations (which are shared across the site), we could extend the theme as well: https://chakra-ui.com/docs/theming/customize-theme#customizing-component-styles
