### ISSUE TITLE
EMA agency page is not loading / loads extremely slow on production

### ISSUE THREAD

**Issue by khaleedah** [opengovsg/askgovsg#310]
**Describe the bug**
Agency page for EMA does not load on production, but is fine on staging.
Sometimes can load but is extremely slow compared to other agency pages.
Tested both on desktop and mobile.

**To Reproduce**
1. Go to 'https://ask.gov.sg/agency/EMA'
2. Compare loading time with 'https://staging.ask.gov.sg/agency/ema'

**Expected behavior**
Page should load on production

**Desktop (please complete the following information):**
 - Chrome

**Smartphone (please complete the following information):**
 - iPhone 12
 - Chrome

**Screenshots**
<img width="1792" alt="Screenshot 2021-09-16 at 10 11 13 AM" src="https://user-images.githubusercontent.com/87360573/133537982-dfc8a4db-193d-47aa-be8a-a5c7ac743849.png">

**Comment by LoneRifle** [comment]
Per discussion, this should not be a code-related matter
