### ISSUE TITLE
questions view count is buggy

### ISSUE THREAD

**Issue by chongzixin** [opengovsg/askgovsg#33]
helpgovsg/server/modules/post/post.service.ts
Lines 312 to 322 in c23acfb

`views` currently increment on every GET of a post. Issues:

- If the same user navigates multiple times to a page, `views` increments
- We refetch questions from the server to keep the data fresh eg. if someone navigates away from the browser then returns, we GET the post again.

**Comment by nauynix** [comment]
Looked into the issue. Every loading makes two `GET` calls - one in `post.component`, and another in its children `postcell.component`. Definitely should only make one call in `post.component` and pass it down. Someone has already marked it as a todo, Ill get around to it soon.

https://github.com/opengovsg/askgovsg/blob/4a42c213a7e760bd76a45e8435c77feab398f29c/client/src/pages/Post/Post.component.jsx#L30-L33

https://github.com/opengovsg/askgovsg/blob/4a42c213a7e760bd76a45e8435c77feab398f29c/client/src/pages/Post/QuestionSection/PostCell/PostCell.component.jsx#L12-L16
