### ISSUE TITLE
Allow for users to go back after a 'Topic' is selected

### ISSUE THREAD

**Issue by khaleedah** [opengovsg/askgovsg#458]
Currently after selecting a `Topic`, users have no way to undo that action and go back to `All Questions` page

Can we add a `Back to all questions`

**Comment by LinHuiqing** [comment]
Something like this temporarily?

https://user-images.githubusercontent.com/37061143/135739464-3c1722e3-c6b3-48a4-b502-1ff16d00c677.mov
