### ISSUE TITLE
Deleted posts are still accessible if post id known

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/askgovsg#487]
**Is your feature request related to a problem? Please describe.**
After a post has been deleted by a user, the same user is still able to view that question on the home page

**Describe the solution you'd like**
List of questions should update automatically after a post has been deleted. Might be worth investigating the caching effects

**Additional context**
Bug reported by Will

**Comment by LoneRifle** [comment]
Deleting a post merely sets its status to `ARCHIVED`. If the post id is still known, an authenticated user can still get to it. Public users would no longer be able to see the post however.

**Comment by LoneRifle** [comment]
Working for now, UI has to be followed up to indicate to authenticated user when a post has been "deleted" (really archived)
