### ISSUE TITLE
Refactor AnswersService to use dependency injection

### ISSUE THREAD

**Issue by LinHuiqing** [opengovsg/askgovsg#646]
**Is your feature request related to a problem? Please describe.**

AnswersService currently does not use dependency injection and instead imports models directly from `../../bootstrap/sequelize`. This will be troublesome when unit tests are being written.

**Describe the solution you'd like**

Refactor code such that these imports:

```ts
import {
  User as UserModel,
  Post as PostModel,
  Agency as AgencyModel,
  Answer as AnswerModel,
} from '../../bootstrap/sequelize'
```

will be passed in as arguments when constructing the module instead.

**Comment by LinHuiqing** [comment]
Same goes for TagsService, but not sure if it will be removed when we migrate to categories.

**Comment by LoneRifle** [comment]
> Same goes for TagsService, but not sure if it will be removed when we migrate to categories.

we'll continue to have tags, as discussed
