### ISSUE TITLE
Suggest a more user friendly image upload feature for agency

### ISSUE THREAD

**Issue by khaleedah** [opengovsg/askgovsg#658]
The current image upload modal is not that intuitive, with options for user to fix the sizing (somewhat confusing). Additionally, user has to fill in alt text before they can upload but there is no message to prompt them to do so.

![image](https://user-images.githubusercontent.com/87360573/138834498-1b5d7dc5-9951-48bd-ad75-a0e849d8ae0b.png)

Design to look into image uploading features to create a better experience for agencies as image upload is quite an important feature for most agencies as well.

**Comment by LoneRifle** [comment]
Fixed in #746
