### ISSUE TITLE
Add elasticsearch to improve user experience

### ISSUE THREAD

**Issue by LinHuiqing** [opengovsg/askgovsg#659]
**Is your feature request related to a problem? Please describe.**

Current problems:

1. Bad search experience as users might be unable to find answers to questions due to search being not robust enough.
2. Search is handled by FuseJS on frontend, meaning that all search entries have to be fetched before search is done. This leads to bad user experience as loading time increases.

**Describe the solution you'd like**

Implement elasticsearch which will hopefully help the 2 issues mentioned above.

Closes #145

**Comment by LoneRifle** [comment]
Closed in favour of articulating this as a project
