### ISSUE TITLE
Display external link out on desktop view

### ISSUE THREAD

**Issue by khaleedah** [opengovsg/askgovsg#794]
![image](https://user-images.githubusercontent.com/87360573/142095670-50b6cee8-f3f6-4fd0-898c-67eaf2c8b2e5.png)

Figma file here:
https://www.figma.com/file/O6lxjjfn04Ow6nn2TMStpk/AskGov-Design-Master-v2?node-id=5932%3A45299

**Comment by LoneRifle** [comment]
Already implemented
