### ISSUE TITLE
On mobile view, banner is blocked for agency home page and question detail page.

### ISSUE THREAD

**Issue by chongzixin** [opengovsg/askgovsg#9]
![image](https://user-images.githubusercontent.com/3539074/127952063-515df4da-3bb6-4e81-a31c-5c0cf78b280f.png)

![image](https://user-images.githubusercontent.com/3539074/127952073-098ed62a-7719-4874-a3e0-f56c916bfc7e.png)

**Comment by chongzixin** [comment]
Hmm.. Actually seems to only happen on iOS Simulator.

**Comment by LoneRifle** [comment]
I think we've uncovered this before, and were unable to reproduce even with other iOS Simulator instances on other machines.
