### ISSUE TITLE
Specify properties of fields when backfilling opensearch index with data

### ISSUE THREAD

**Issue by LinHuiqing** [opengovsg/askgovsg#945]
**Is your feature request related to a problem? Please describe.**

Fields indexed on OpenSearch currently have very loosely defined properties, i.e. numbers like ids are specified to be of `float` type, when the `integer` type would be enough. Specifying types which will help to [improve indexing and searching efficiency](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/number.html).

**Describe the solution you'd like**

Specify field types as properties when backfilling opensearch.

**Additional context**

To check for properties of fields, simply use `curl --insecure -u 'admin:admin' -XGET 'https://localhost:9200/search_entries/'`.

<img width="1104" alt="Screenshot 2021-12-14 at 10 17 59 AM" src="https://user-images.githubusercontent.com/37061143/145921052-7621ad8c-96f2-47a9-8712-02b32c43ce6a.png">

**Comment by christopherlim98** [comment]
Closing issue, see discussion in #1008.
