### ISSUE TITLE
Add progress bar to opensearch index backfill script

### ISSUE THREAD

**Issue by LinHuiqing** [opengovsg/askgovsg#946]
**Is your feature request related to a problem? Please describe.**

Opensearch index backfill script currently does not give any indicator that it is running when it is. This is anxiety-inducing for developers :(

**Describe the solution you'd like**

Add a progress bar for when the script is running or at least some other indication that it is doing so (loading spinner maybe?)

**Comment by LoneRifle** [comment]
Just logging indexed entries is fine =)

**Comment by LinHuiqing** [comment]
Its a bulk operation though, so the request doesn't return a response until its completely done :')

**Comment by LoneRifle** [comment]
ah, if that's the case, then I guess there's not much we can do. You may want to at least log the stages of execution the script goes through, eg, querying from db, transforming results, pushing to opensearch, etc
