### ISSUE TITLE
Port 5000 already in use by AirPlay on macOS 12

### ISSUE THREAD

**Issue by zxt-tzx** [opengovsg/askgovsg#992]
**Description**
Port 5000 used as the server port in the project is already in use by AirPlay on macOS 12. As such, when I run `npm run dev`, this the following error message is shown:
[ERROR] 14:44:54 Error: listen EADDRINUSE: address already in use :::5000
![image](https://user-images.githubusercontent.com/67887489/146724275-baf11501-da4c-458a-84c2-b02a7ab515a4.png)

**Additional context**
Brief Googling reveals that this is an issue with Apple using port 5000 for AirPlay Receiver. See [here](https://developer.apple.com/forums/thread/682332) and [here](https://www.reddit.com/r/webdev/comments/qg8yt9/apple_took_over_port_5000_in_the_latest_macos/). 

I don't fully understand this, but apparently this is [not an unreasonable decision](https://www.reddit.com/r/webdev/comments/qg8yt9/comment/hi65w7i/):
> Just did a bit more digging, and IANA actually assigns port 5000 to "commplex-main" - so really any other service that's using that port is violating the official assignment. Based on a quick search of what commplex-main is, it's related to UPnP for network device discoverability. I'm not sure exactly what the AirPlay Receiver service does, but I get the gist that it probably does fit somewhere into the scope of UPnP-related features. At the very least, it's probably a far more accurate usage of port 5000 than some random dev servers.

**Solution**
A quick way to fix the problem is to disable AirPlay Receiver in System Settings > Sharing. 

However, I was thinking a better solution might be to simply use a different port number for the server. If I'm not mistaken, we can just use another port number that is less likely to result in such conflicts? If so, happy to submit a PR to change all instances of 5000 to, say, another randomly chosen port number.

**Comment by LoneRifle** [comment]
No intentions to move away from port 5000, as it's dev convention to use ExpressJS. You may wish to add a note to the README to disable the port, instructions as detailed above.

**Comment by zxt-tzx** [comment]
I'm partial to changing the port number (#1020) instead of just amending the README (#1019)! Have created two PRs but only one should be merged.
